{
 "title": "JWT-Pizza-Service Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pizzas_sold_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU and Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_total", "legendFormat": "CPU" },
    { "expr": "memory_usage_total", "legendFormat": "Memory" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(requests_total[30s])", "legendFormat": "{{endpoint}}" }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_request_total[30s]))",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(http_request_total{method=\"GET\"}[30s])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(http_request_total{method=\"POST\"}[30s])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(http_request_total{method=\"PUT\"}[30s])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(http_request_total{method=\"DELETE\"}[30s])",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(request_latency_total[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(auth_attmepts_total{success=\"true\"}[30s])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(auth_attmepts_total{success!=\"true\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "count(active_users_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "rate(pizzas_sold_total[30s])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  }
 ]
}